### PR TITLE
Update MLIR version to current HEAD

### PR DESCRIPTION
**Pull request by Menooker**
This PR targets to enable downstream repos to use MLIR main branch, along with IMEX. Upstream MLIR has some breaking changes:
 * Removed legacy bufferizaton
 * Removed legacy GPU module to binary

This PR adapts IMEX for these changes. Note that I am still using the legacy way of attaching SPIRV binary to an attr of GPU module. Upstream now prefers gpu.binary way. Maybe we need to switch to that in another PR.

### CODE REVIEW

**Comment by Menooker** [comment]
Failed Tests (11):
  IMEX :: Conversion/NDArrayToLinalg/NDArrayToLinalg.mlir
  IMEX :: Jax/gordon/jit__logsm_from_logmhalo_jax_kern_0_before_linalg.mlir
  IMEX :: Models/Mobilenet-v3/mobilenetv3-linalg-without-tensor-pad.mlir
  IMEX :: Models/Mobilenet-v3/mobilenetv3-linalg.mlir
  IMEX :: PlaidML/OpTest.GEMM_FLOAT32.mlir
  IMEX :: PlaidML/OpTest.GEMV_FLOAT32.mlir
  IMEX :: PlaidML/OpTest.Shape.mlir
  IMEX :: Transforms/vector-linearize.mlir
  IMEX :: imex-runner/gpu_runner.mlir
  IMEX :: imex-runner/ndarray_bcast.mlir
  IMEX :: imex-runner/ndarray_ops.mlir


Testing Time: 337.82s

Total Discovered Tests: 279
  Unsupported:   1 (0.36%)
  Passed     : 267 (95.70%)
  Failed     :  11 (3.94%)

**Comment by Menooker** [comment]
Most of failed tests are related to NDArray, explicitly using bufferization Ops, and upstream Op schema changes:

```
custom op 'tensor.expand_shape' expected 'output_shape'
```

It is kind of out of the scope of mine.

**Comment by kurapov-peter** [comment]
I think this is done, right @Menooker?

**Comment by Menooker** [comment]
> I think this is done, right @Menooker?

Yes. It is. Let's close this PR.

**Pull request closed without merging**
