### PR TITLE
[Test] add select set of PlaidML test lowered to linalg dialect

### PR DESCRIPTION
**Pull request by Dewei-Wang-sh**
these tests are more of unit test compared to what sang lk is adding.
For now, there are roughly 10 categories:
- elementwise : CppEdsl.EltwiseAdd.mlir
- broadcast : OpTest.BroadcastNonNumpy.mlir
- transpose : OpTest.Transpose.mlir
- reduction : OpTest.Sum.mlir
- gemm : CppEdsl.DotF16.mlir, CppEdsl.Dot.mlir
- gemV : ExampleCppEdsl.GEMV_FLOAT32.mlir
- quantize : ExampleCppEdsl.Quantize.mlir
- pad op : OpTest.ExplicitPaddingInf.mlir
- conv op : ExampleCppEdsl.Conv1D.mlir
- softmax : OpTest.Softmax.mlir

Since this is operation level test, it can function as a start to verify our lowering path.

Lit test is disabled for the new directory by updating lit.cfg.py
Tests are raw mlir files without any RUN command or CHECK directives.
Test enabling will be done incrementally in the future.
Input and golden output needs to be added to test cases to enable end to end execution.
Since this is the initial set, more test may be added in the future.

Please review these guidelines to help with the review process:
- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [x] If this PR is a work in progress, are you filing the PR as a draft?
- [x] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Review by mshahneo — CHANGES_REQUESTED** [review]
@Dewei-Wang-sh , could you please add the instructions to run the tests at the top of each files (upstream MLIR style)?

**Comment by Dewei-Wang-sh** [comment]
> @Dewei-Wang-sh , could you please add the instructions to run the tests at the top of each files (upstream MLIR style)?

Test enabling will be done incrementally in the future, currently these are plain tests

**Comment by silee2** [comment]
linalg.init_tensor [] is now replaced with tensor.empty()
Btw, I enabled cpu end to end for one test case in #350

**Comment by silee2** [comment]
You can support incremental enabling by appending list of tests that should not run to "config.excludes" in "lit.local.cfg"
lit.local.cfg is a per (sub)directory configuration file that refines lit config.

**Comment by Dewei-Wang-sh** [comment]
close this pr since chao create another pr on top of this.

**Pull request closed without merging**
