### PR TITLE
Add select set of Argonne Jax test lowered to linalg dialect.

### PR DESCRIPTION
**Pull request by silee2**
This is the initial set of mlir test cases from Argonne Jax
Lit test is disabled for the new directory by updating lit.cfg.py
Tests are raw mlir files without any RUN command or CHECK directives.
Test enabling will be done incrementally in the future.
Input and golden output needs to be added to test cases to enable end to end execution.
Since this is the initial set, more test may be added in the future.
Also added resnet-50 and mobilenet-v3 models in linalg dialect.

Please review these guidelines to help with the review process:
- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
- [x] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Review by mshahneo — COMMENTED** [review]
Looks good to me.
One quick question, @silee2 : Do all these tests run? The reason I am asking is that, will they be part of CI?

**Comment by silee2** [comment]
> Looks good to me. One quick question, @silee2 : Do all these tests run? The reason I am asking is that, will they be part of CI?

They won't be part of CI initially. The tests are meant from end to end flow which is still under development for refactor branch. lit.cfg.py excludes these new directory from testing. They will be enabled over time.

**Review by Dewei-Wang-sh — APPROVED** [review]
lgtm

**Comment by silee2** [comment]
> Can we remove the module__* from the file names and just have the functionality to make it more readable?

Removed.

**Pull request merged**
