### PR TITLE
Adding more precise path detection in FindSyclRuntime.cmake

### PR DESCRIPTION
**Pull request by Garra1980**
Please review these guidelines to help with the review process:
- [ ] Have you provided a meaningful PR description?
- [ ] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
- [ ] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Review by leshikus — APPROVED** [review]
I believe there should be more reliable way to extract the version than using the path

otherwise, the patch looks good

**Review by leshikus — APPROVED** [review]
LGTM

**Review by chencha3 — APPROVED** [review]
LGTM

**Review by mshahneo — COMMENTED** [review]
LGTM

**Pull request merged**
