### PR TITLE
Update LLVM SHA

### PR DESCRIPTION
**Pull request by nbpatel**
Please review these guidelines to help with the review process:
- [ ] Have you provided a meaningful PR description?
- [ ] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
- [ ] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Comment by nbpatel** [comment]
@fschlimb can you fix the two failing Ptensor test cases and push the fix here?

**Comment by silee2** [comment]
> @fschlimb can you fix the two failing Ptensor test cases and push the fix here?

@nbpatel I pushed the fix.

**Review by silee2 — APPROVED** [review]
LGTM

**Comment by silee2** [comment]
Updating LLVM to same version as #540

**Review by fschlimb — APPROVED** [review]

**Pull request merged**
