### PR TITLE
Introduce device/environment region op

### PR DESCRIPTION
**Pull request by Hardcode84**
* Introduce `EnvironmentRegionOp` and corresponding `EnvironmentRegionYieldOp` terminator.
* Renamed from previous `device_region` proposal to `env_region` as it is not strictly tied to the device (e.g. GPU) execution.
* This PR only introduces op definition and some basic printing/parsing tests.
* For the specific op semantics see op description in td file.

### CODE REVIEW

**Review by fschlimb — COMMENTED** [review]
Is there a way to have the printing and parsing code get auto-generated?

**Comment by Hardcode84** [comment]
> Is there a way to have the printing and parsing code get auto-generated?

Not for the ops which manipulate regions as far as I know.

**Comment by Hardcode84** [comment]
Can we get review on actual semantics? It is blocking further work, and we don't have any comment on semantics I would prefer it to be merged and any potential minor issues like actual text formatting fixed postfactum.

**Comment by fschlimb** [comment]
> Can we get review on actual semantics? It is blocking further work, and we don't have any comment on semantics I would prefer it to be merged and any potential minor issues like actual text formatting fixed postfactum.

We have a RFC #283 which is intended to define the semantics. You are welcome to call a separate RFC if you prefer a separate document for this.

**Comment by Hardcode84** [comment]
This is much better than RFC, because it shows actual code, which can be compiled and run. But you can consider op description in td file as 'RFC'.

**Comment by Hardcode84** [comment]
If there aren't any further questions I'm going to merge this.

**Pull request merged**
