### PR TITLE
Fix IMEX config and installation issues.

### PR DESCRIPTION
**Pull request by silee2**
Fix issues with IMEXConfig.cmake and IMEXTargets.cmake and installation issues.
Should be able to replace #290
Some imported cmake functions(add_mlir_* ) are redefined for the fix.
Added new macro add_mlir_tool() that is used for handling imex-opt installation.
Added an example CMake project using external IMEX under "integration/example"

Also includes some changes to 
- header inclusion
- install rules
- cleanup cmake file (remove unused variables)

Please review these guidelines to help with the review process:
- [ ] Have you provided a meaningful PR description?
- [ ] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
- [ ] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Comment by silee2** [comment]
@fschlimb This PR should address #290

**Comment by silee2** [comment]
Converting back to draft since imex-opt does not get installed.

**Comment by silee2** [comment]
Fixed imex-opt install issue.

**Review by fschlimb — APPROVED** [review]
I tried this with my external library project and it works like charm!

Thanks so much for fixing this!

**Review by nbpatel — APPROVED** [review]

**Pull request merged**
