### PR TITLE
fixes for install rules

### PR DESCRIPTION
**Pull request by fschlimb**
Please review these guidelines to help with the review process:
- [x] Have you provided a meaningful PR description?
- [ ] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [x] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
- [x] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Comment by fschlimb** [comment]
@diptorupd we should add changes needed for #289 here

**Comment by diptorupd** [comment]
@fschlimb Let me try it out locally.

**Comment by Hardcode84** [comment]
I highly recommend to merge related changes back to `main ` later.
Python frontend development will continue in `main`. We are not moving to refactor anytime soon (and most likely never will).

Have a nice day.

**Comment by fschlimb** [comment]
> I highly recommend to merge related changes back to `main` later. Python frontend development will continue in `main`. We are not moving to refactor anytime soon (and most likely never will).
> 
> Have a nice day.

@Hardcode84 I don't follow, this is not about main at all. What do you mean?

**Comment by Hardcode84** [comment]
I mean not specifically this PR, but all cmake/scripts/etc changes.

**Comment by diptorupd** [comment]
@fschlimb I investigated the issue. Unfortunately, not closer to a solution yet.

I have some observations:

1. My reading of what the `IMEXTargets.cmake` should do is to indicate to an external CMake project the location of local IMEX libraries.
2. When I compare the `IMEXTargets.cmake` to `MLIRTargets.cmake` I see one difference: `IMEXtargets.cmake` does not provide any `expectedTarget` the list is empty.

**IMEXTarget.cmake**
> set(_expectedTargets)
foreach(_expectedTarget )
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()

**MLIRTarget.cmake**
> foreach(_expectedTarget MLIRAnalysis MLIRPresburger MLIRAffineToStandard MLIRAMDGPUToROCDL MLIRArithmeticToLLVM MLIRArithmeticToSPIRV MLIRArmNeon2dToIntr ...)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()



Based on the above, could it be that CMake skips the installation of the file because it is smart enough to detect that there are no targets exported by IMEX? If that is the case, the issue will be in something like `IMEX_ADD_LIBRARY` and not directly in `IMEXtargets.cmake`.

**Comment by diptorupd** [comment]
It might be worth going to LLVM discourse to ask for advise, maybe even our dpcpp build team.

**Comment by fschlimb** [comment]
@diptorupd any progress on this? I would like to provide @chudur-budur with a way to use my tensor library for functional testing/experiments which needs a way to properly install imex.

**Comment by fschlimb** [comment]
Superseded by #553

**Pull request closed without merging**
