### PR TITLE
Change imex-runner.py pass pipeline file comment from Python style

### PR DESCRIPTION
**Pull request by silee2**
comment to C++ style comment

Please review these guidelines to help with the review process:
- [ ] Have you provided a meaningful PR description?
- [ ] Have you added a test, a reproducer, or a reference to an issue with a reproducer?
- [ ] Have you tested your changes locally for CPU and GPU devices?
- [ ] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?
- [ ] Have you organized your commits logically and ensured each can be built by itself?

### CODE REVIEW

**Comment by silee2** [comment]
pass pipeline lacks documentation on syntax. Documentation will be added in a separate PR. Created an issue to track it. #539

**Review by mshahneo — APPROVED** [review]
LGTM

**Review by nbpatel — COMMENTED** [review]
Just one point...usually dont the python files use # for comments? So I thought # made more sense in this case...// is usually used for .c, .cpp files... maybe I am wrong

**Comment by silee2** [comment]
> Just one point...usually dont the python files use # for comments? So I thought # made more sense in this case...// is usually used for .c, .cpp files... maybe I am wrong

@nbpatel Yes "#" makes more sense for comment. And that is why I used "#" originally. But mlir pass options include using "#" as a character so had to pick something else for comment.

**Review by nbpatel — APPROVED** [review]
LGTM

**Pull request merged**
